# Generated by Django 5.2 on 2025-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('first_name_en', models.CharField(max_length=100, null=True)),
                ('first_name_uz', models.CharField(max_length=100, null=True)),
                ('first_name_ru', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(max_length=100, null=True)),
                ('last_name_uz', models.CharField(max_length=100, null=True)),
                ('last_name_ru', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('slug_en', models.SlugField(null=True, unique=True)),
                ('slug_uz', models.SlugField(null=True, unique=True)),
                ('slug_ru', models.SlugField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
