# Generated by Django 5.2 on 2025-04-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_bio_en_author_bio_ru_author_bio_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio_ru',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio_uz',
        ),
        migrations.RemoveField(
            model_name='author',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='author',
            name='slug_uz',
        ),
    ]
