# Generated by Django 5.2 on 2025-04-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher_ru',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher_uz',
        ),
    ]
