# Generated by Django 5.2 on 2025-04-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_book_en_review_book_ru_review_book_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_uz',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name_uz',
        ),
    ]
