# Generated by Django 5.2 on 2025-04-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stock', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookavailability',
            name='book_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookavailability',
            name='book_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookavailability',
            name='book_uz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='books.book'),
        ),
    ]
